web:
  container_name: polyplot
  build: .
  volumes:
   - .:/root
  ports:
   - 5000:5000
  links:
   - mongo

jupyter:
  container_name: notebook
  image: jupyter/minimal-notebook:latest
  ports:
   - 8888:8888
  links:
   - mongo

mongo:
  container_name: database
  image: mongo:3.0.2
  ports:
   - 27017:27017
